### ISSUE TITLE
请问当图片插入到一定数量的时候出现oom怎么解

### ISSUE THREAD

**Issue by liulinsen** [sendtion/XRichText#1]

**Comment by EdwardSituwende** [comment]
请问你是插入了多少张图片？

**Comment by liulinsen** [comment]
大概30多张的样子

**Comment by liulinsen** [comment]
目前我没有用bitmap，用的是将当前的imageview返回然后在项目里用的图片加载库实现的设置图片

**Comment by sendtion** [comment]
@liulinsen 如果可以自己修改一下。我这边已经优化完毕，我有时间更新一下。

**Comment by liulinsen** [comment]
@sendtion 你怎么做的？能给我说一下吗  我借鉴一下

**Comment by sendtion** [comment]
![image](https://cloud.githubusercontent.com/assets/9346618/23248573/ef93f11e-f9da-11e6-8b22-d4cb0e25ad5f.png)

@liulinsen 
//imageView.setImageBitmap(bmp);这里使用Glide加载图片
//imageView.setBitmap(bmp);//去掉这个防止bitmap一直被占用，导致内存溢出

**Comment by liulinsen** [comment]
@sendtion 我用的加载库是imageloader  应该也可以的吧

**Comment by sendtion** [comment]
@liulinsen 应该也是可以的。我已经更新到1.1版本了，可以直接引用~

**Comment by liulinsen** [comment]
@sendtion 我试了用glide，在图片加载到80张仍然oom了

**Comment by sendtion** [comment]
@liulinsen 我用Demo测试30多张是没问题的，大概100多M，没有测试更多图片。话说你要做什么啊，插入那么多图片？

**Comment by liulinsen** [comment]
@sendtion 就是编辑文章那种

**Comment by sendtion** [comment]
@liulinsen 你试试demo会不会崩溃，不会的话你可以按照demo的方式使用rxjava。我在自己的项目中插入70多张也可以流畅运行的。你再看一下自己的项目是不是占用内存太高了，优化一下。

**Comment by liulinsen** [comment]
我项目里内存占用有点高，我再去想想办法吧，谢谢
