### ISSUE TITLE
删除图片问题

### ISSUE THREAD

**Issue by 757027949** [sendtion/XRichText#11]
这个删除图片也是删除当前文本里面的把  我刚看见源码的时候  本地的文件都删了 这个不应该把...

**Comment by sendtion** [comment]
这个需要你自己处理一下，如果你插入图片的时候，把图片保存到了新的目录就可以实现删除，如果用的直接是图库中的地址，你可以不要删除它

**Comment by sendtion** [comment]
Demo中是把插入的图片保存在了APP目录，所以删除笔记时也删除了图片。最新1.2版本通过接口开放了图片删除操作，可以再编辑笔记时，自己实现删除操作。
