### ISSUE TITLE
插入图片后文字丢失问题

### ISSUE THREAD

**Issue by zhupengxiang** [sendtion/XRichText#14]
如果我在输入的文字中间插入图片后，光标选中后的文字就没了，这个怎么解决

**Comment by Richard0403** [comment]
It's no problem when you insert first image, but some text will be removed if insert other images.
I found the wrong code in "insertImage" method of RichTextEditor,
It's the fixed code.

`   public void insertImage(String imageUrl) {
        String lastEditStr = lastFocusEdit.getText().toString();
        int cursorIndex = lastFocusEdit.getSelectionStart();
        String editStr1 = lastEditStr.substring(0, cursorIndex).trim();
        int lastEditIndex = allLayout.indexOfChild(lastFocusEdit);

        if (lastEditStr.length() == 0 || editStr1.length() == 0) {
            // 如果EditText为空，或者光标已经顶在了editText的最前面，则直接插入图片，并且EditText下移即可
            addImageViewAtIndex(lastEditIndex, imageUrl);
        } else {
            // 如果EditText非空且光标不在最顶端，则需要添加新的imageView和EditText
//            lastFocusEdit.setText(editStr1);
//            String editStr2 = lastEditStr.substring(cursorIndex).trim();
//            if (editStr2.length() == 0) {
//                editStr2 = " ";
//            }
//            if (allLayout.getChildCount() - 1 == lastEditIndex) {
//                addEditTextAtIndex(lastEditIndex + 1, editStr2);
//            }
//
//            addImageViewAtIndex(lastEditIndex + 1, imageUrl);
//            lastFocusEdit.requestFocus();
//            lastFocusEdit.setSelection(editStr1.length(), editStr1.length());//TODO

            lastFocusEdit.setText(editStr1);
            String editStr2 = lastEditStr.substring(cursorIndex).trim();
            addImageViewAtIndex(lastEditIndex + 1, imageUrl);
            if (editStr2.length() == 0) {
                editStr2 = " ";
            }else{
                addEditTextAtIndex(lastEditIndex + 2, editStr2);
            }
            lastFocusEdit.requestFocus();
            lastFocusEdit.setSelection(editStr1.length(), editStr1.length());//TODO
        }
        hideKeyBoard();
    }
`

**Comment by zhupengxiang** [comment]
thank you very much。哈哈
