### ISSUE TITLE
你好 关于androidstudio2.3.3不能使用问题

### ISSUE THREAD

**Issue by JonsonBob** [sendtion/XRichText#15]
如题
如果可以 我希望能加QQ 方便发一写错误截图 1525089850

**Comment by sendtion** [comment]
Android Studio应该有错误提示的，按照提示修改即可。
一般是gradle版本问题，或者是support library库版本问题
如有其它疑问，可以加我qq:524100248

**Comment by JonsonBob** [comment]
嗯嗯 你好 我已经加了你你的 QQ 希望您能够同意
