### ISSUE TITLE
插入图片报错

### ISSUE THREAD

**Issue by positiveBOY** [sendtion/XRichText#23]
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.lede.chuang-2/base.apk)

**Comment by sendtion** [comment]
引入Glide了吗？也可能是Glide版本问题

**Comment by positiveBOY** [comment]
应该是glide版本问题   ，大佬要不要考虑升一下glide的版本啊，有时候我们项目里一些第三方库被动的要引入glide。版本低了就不太好兼容

**Comment by sendtion** [comment]
@positiveBOY 可以呢，我抽时间更新下

**Comment by positiveBOY** [comment]
这么快。。。哈哈哈
