### ISSUE TITLE
RichTextView图片点击事件

### ISSUE THREAD

**Issue by positiveBOY** [sendtion/XRichText#25]
用RichTextView显示图文的时候需要点击加载大图，我有看到RichTextView的代码里可以设置点击事件，但是不太好判断被点击的图片的position

**Comment by sendtion** [comment]
对的，我也没找到合适的方式判断position，所以先取消了。等后续有较好的方案再加入

**Comment by sendtion** [comment]
@positiveBOY 你好，新版本 v1.4 已支持点击图片查看大图。开放了接口可以自己实现，具体请参考Demo
