### ISSUE TITLE
添加的图片左右边缘被裁剪

### ISSUE THREAD

**Issue by hondorchen** [sendtion/XRichText#26]
编辑富文本的时候，插入图片发现原图的左右边缘被裁掉了

**Comment by sendtion** [comment]
嗯，我也发现了，等我查一下原因

**Comment by chenhon** [comment]
这个是这两处导致的：
1、allLayout.setPadding(50, 15, 50, 15);//设置间距
 2、imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);//裁剪剧中

        // 调整imageView的高度，根据宽度来调整高度
        Bitmap bmp = BitmapFactory.decodeFile(imagePath);
        int imageHeight = 500;
        if (bmp != null) {
            imageHeight = allLayout.getWidth() * bmp.getHeight() / bmp.getWidth();
            bmp.recycle();
        }
        // TODO: 17/3/1 调整图片高度，这里是否有必要，如果出现微博长图，可能会很难看
        RelativeLayout.LayoutParams lp = new RelativeLayout.LayoutParams(
                LayoutParams.MATCH_PARENT, imageHeight);//设置图片固定高度
        lp.bottomMargin = 10;
        imageView.setLayoutParams(lp);

CENTER_CROP的意思是对原图居中显示后进行等比放缩处理，使原图最小边等于ImageView的相应边。
然后你对allLayout设置了左右内边距，在计算图片高度的时候是算上了这个内边距的，这样就导致图片按照CENTER_CROP显示的时候左右边缘进入了allLayout的内边距里面。

我的解决方案：
首先设置左右内边距为0：allLayout.setPadding(0, 15, 0, 15);//设置间距
然后在使用富文本编辑器时设置 android:paddingHorizontal="50dp"

**Comment by sendtion** [comment]
这个问题已修复
