### ISSUE TITLE
图片显示异常

### ISSUE THREAD

**Issue by zou-xian-liang** [sendtion/XRichText#28]
1、添加图片时，同时添加多张，且图片比例不一样
2、保存之后进入查看，发现图片的高度跟第一张一样了，进行了拉伸。

如果单次插入单张图片就不会出现这样的情况

**Comment by sendtion** [comment]
收到，我会查一下是什么问题

**Comment by sendtion** [comment]
@zou-xian-liang 你好，你说的问题已经解决，请使用1.5版本

**Comment by zou-xian-liang** [comment]
恩，好的；
我这边根据项目需要已经修改了，感谢大佬开源
