### ISSUE TITLE
RecyclerView中显示异常

### ISSUE THREAD

**Issue by zou-xian-liang** [sendtion/XRichText#29]
在RecyclerView中每个item后面都会多出一段空白不知道是什么情况；

如果是单独页面中只放一个richText就不会有问题

**Comment by sendtion** [comment]
没有在RecyclerView测试过，应该是有问题的，此开源库应用场景不在于此

**Comment by zou-xian-liang** [comment]
恩，问题已解决，是在构造方法中添加了一个View到容器中了，去除就可以了
