### ISSUE TITLE
插入图片后光标能自动去最底下的一个EditText吗

### ISSUE THREAD

**Issue by TopTime1** [sendtion/XRichText#3]
插入图片后光标能自动去最底下的一个EditText吗

**Comment by TopTime1** [comment]
好

**Comment by Billxxxx** [comment]
我看好像用ScrollView的方法应该就可以了吧，等下上代码

**Comment by 757027949** [comment]
((ViewGroup) et_new_content.getChildAt(0)).getChildAt(et_new_content.getLastIndex() - 1).requestFocus();//当前文本获取焦点

**Comment by sendtion** [comment]
最近有时间更新了一下，最新1.2版本更完善，修复了这个问题，插入图片后光标在最后。
