### ISSUE TITLE
Demo跑了下插入图片有问题，我选择一张图，结果默认还插入另一张小女孩的图片

### ISSUE THREAD

**Issue by richfuns** [sendtion/XRichText#31]

**Comment by richfuns** [comment]
另一张图片的代码：
<img src="http://p695w3yko.bkt.clouddn.com/18-5-5/30271511.jpg"/>

**Comment by sendtion** [comment]
在NewActivity.java文件中，第440行，把这一行去掉即可。这是插入了一张网络图片进行测试，你可以去看看代码。

https://github.com/sendtion/XRichText/blob/443de6ee5939a573daf55cd70d22dbafe2517744/app/src/main/java/com/sendtion/xrichtextdemo/ui/NewActivity.java#L440
