### ISSUE TITLE
图片显示旋转

### ISSUE THREAD

**Issue by Fyyvictory** [sendtion/XRichText#35]
您好，发现以下问题：
1、测人人员反馈说有的图片加载显示方向和原图不同；我搜索了一下，需要在js中获取一下图片的exif参数，然后判断角度再显示。
2、如果image的path中包含“+”；在insertimage的方法之后，“+”会被替换成空格，这个貌似是js执行时特殊字符替换了

**Comment by sendtion** [comment]
图片地址可以自己设置，而且path中怎么会出现+呢？这个是xrichtext存在的问题吗？

**Comment by Fyyvictory** [comment]
首先很抱歉，问题2并非xrichtext中发现的，我down好几个富文本编辑的代码，弄混了；其次，也是很偶然的发现一些图片的名称中含有一些特殊字符，如‘/’  '+'这些，加载的时候需要结合项目需求解码和编码。不好意思，耽误你的时间啦~~
