### ISSUE TITLE
Duplicate jar entry [com/bumptech/glide/b.class]

### ISSUE THREAD

**Issue by itzihao** [sendtion/XRichText#47]
//富文本
    implementation ('com.github.sendtion:XRichText:1.8') {
        exclude group: 'com.android.support'
        exclude group: 'com.github.bumptech.glide'
    }

**Comment by sendtion** [comment]
如果你的项目中用的Glide是4.0以上版本，建议直接使用库中的，就不要排除掉了。

**Comment by itzihao** [comment]
感谢，完美解决修复了。
