### ISSUE TITLE
图片点击事件

### ISSUE THREAD

**Issue by zivids** [sendtion/XRichText#5]
没有图片点击事件吗？

**Comment by sendtion** [comment]
图片点击事件，你可以自行修改源码。
示例：
在RichTextView和RichTextEditor中，生成图片View时，给图片设置监听事件。
`

    private RelativeLayout createImageLayout() {
        RelativeLayout layout = (RelativeLayout) inflater.inflate(
                R.layout.edit_imageview, null);
        layout.setTag(viewTagIndex++);
        View closeView = layout.findViewById(R.id.image_close);
        closeView.setVisibility(GONE);
        View imageView = layout.findViewById(R.id.edit_imageView);
	imageView.setOnClickListener(btnListener);
        return layout;
    }

`
在构造方法中，实现监听方法。
`

btnListener = new OnClickListener() {

            @Override
            public void onClick(View v) {
                //Toast.makeText(getContext(),"点击图片",Toast.LENGTH_SHORT).show();
                //点击图片预览
                PhotoPreview.builder()
                        .setPhotos(imagePaths)
                        .setCurrentItem(0)
                        .setShowDeleteButton(false)
                        .start(activity);
            }
        };

`
