### ISSUE TITLE
Glideapp依赖报错

### ISSUE THREAD

**Issue by protectedMan** [sendtion/XRichText#52]
![image](https://user-images.githubusercontent.com/17565737/56074609-2c631e80-5de8-11e9-9c35-b3503c40a909.png)
![image](https://user-images.githubusercontent.com/17565737/56074615-39800d80-5de8-11e9-886e-cb7b05cce377.png)

**Comment by liu12151407** [comment]
将glide升级成4.9试一试

 implementation 'com.github.bumptech.glide:glide:4.9.0'
 annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'

**Comment by sendtion** [comment]
如果你的Glide版本在4.0以下，在依赖时加入排除语句：
`exclude group: 'com.github.bumptech.glide`
如果你的Glide版本在4.0以上，在依赖时可以加入排除语句，也可以直接使用库中的Glide版本。
如果发生错误，请Rebuild试试.
