### ISSUE TITLE
RichTextEditor  rtImageHeight设置为0时加载网络图片加载不出来

### ISSUE THREAD

**Issue by protectedMan** [sendtion/XRichText#53]

**Comment by sendtion** [comment]
不会啊，设置为0是显示图片原始高度的

**Comment by DituLin** [comment]
由于是网络图片，得到 bitmap 为 null ，在 rtImageHeight == 0 时，执行

imageHeight = layoutWidth * bmp.getHeight() / bmp.getWidth();

会报 NPE ，所以显示不出来，可以参考 RichTextView 区分是否是网络图片进行处理
