### ISSUE TITLE
AppGlideModule冲突

### ISSUE THREAD

**Issue by jcr1992** [sendtion/XRichText#54]
我发现XRichText直接在内部定义了一个MyGlideModule extends APPGlideModule，导致我无法在项目内另行自定义APPGlideModule，希望之后的版本能更改成LibraryGlideModule

**Comment by sendtion** [comment]
你不用再定义了吧，既然用的Glide4.0以上版本，直接用我库中的就行，不用排除掉了
`
implementation ('com.github.sendtion:XRichText:1.9.0') {
    exclude group: 'com.android.support'
}
`

**Comment by jcr1992** [comment]
我在项目里碰到的问题是我需要重写APPGlideModule里的这个function
public void registerComponents(@NonNull Context context, @NonNull Glide glide,
      @NonNull Registry registry) {}
然后发现你的代码里有一个APPGlideModule了，所以产生了问题

**Comment by sendtion** [comment]
明白了，我看看怎么解决

**Comment by sendtion** [comment]
XRichText中定义了MyGlideModule 继承于APPGlideModule，但是没有实现东西。
所以，你可以继承我的MyGlideModule，处理你的实现。
