### ISSUE TITLE
图片文字错位问题

### ISSUE THREAD

**Issue by Aoi-hosizora** [sendtion/XRichText#62]
+ 问题：插入了几张图片，然后在弹出输入法后偶尔会出现错位（我是删除了一张图片后再插入的文字）
![image](https://user-images.githubusercontent.com/31433480/62765882-b172f180-bac3-11e9-8204-b1d58629db0c.png)

**Comment by sendtion** [comment]
必现吗？

**Comment by sendtion** [comment]
我看你用的模拟器，真机出现吗

**Comment by Aoi-hosizora** [comment]
真机还没出现过，模拟器也是偶尔才会。

弹出输入法的时候刚好遮到文字部分然后文字就直接错位到最上面去了。

**Comment by sendtion** [comment]
被输入法顶上去了，你需要在清单文件中配置activity属性
