### ISSUE TITLE
 UncaughtException detected: java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by wushangjun** [sendtion/XRichText#8]
UncaughtException detected: java.lang.IllegalArgumentException: width and height must be > 0

请问怎么解决?

测试数据:<p><img src=\"http://app11.yuedongkeji.cn/res/image/20170606/14967306785596882888.png\" style=\"width:100%\"></p>

**Comment by sendtion** [comment]
错误说的是宽或者高为0了，你可以把style去掉试试
